### ISSUE TITLE
Plugin Helper not found

### ISSUE THREAD

**Issue by ghost** [cewi/excel#16]
I have just installed the plugin in my local environment and succesful created the first downloads to excel. After tranfering it to the production server, it is not finding the helper class on the path where it is indead.
I have followed the short discription found here.
Changes made in 
bootstrap.php
routes.php
appcontroller.php
as your advices.
Could you give an additional hint please?

**Comment by cewi** [comment]
Sorry for being off and therefore not reacting sooner. Sounds like a Plugin Misconfiguration. Please check that carefully. Can you please paste the exact Error Message then?
One more Idea: Do you develop on windows? Then you could run in issues because Linux on production servers is case-sensitive on paths while Windows is not. Similar effects could be caused on wrong access-rights on the files, where Linux is also "pickier".
So if you developing locally on windows, you should check this points too.

HTH
Cewi
