### ISSUE TITLE
Call to a member function getIndex()

### ISSUE THREAD

**Issue by vishalJS15318** [cewi/excel#21]
"I encountered an error when creating a report: 'Call to a member function getIndex()'
Error
024-06-20 16:13:41 Error: [Error] Call to a member function getIndex() on null (/var/www/html/admin/vendor/Cewi/Excel/src/View/ExcelView.php:122)
#0 /var/www/html/admin/vendor/Cewi/Excel/src/View/ExcelView.php(103): Cewi\Excel\View\ExcelView->__output()
#1 /var/www/html/admin/vendor/cakephp/cakephp/src/Controller/Controller.php(795): Cewi\Excel\View\ExcelView->render()
#2 /var/www/html/admin/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(369): Cake\Controller\Controller->render()
#3 /var/www/html/admin/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage()
#4 /var/www/html/admin/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage()
#5 /var/www/html/admin/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(116): Cake\Error\ExceptionRenderer->render()
#6 /var/www/html/admin/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException()
#7 /var/www/html/admin/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke()
#8 /var/www/html/admin/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke()
#9 /var/www/html/admin/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke()
#10 /var/www/html/admin/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke()
#11 /var/www/html/admin/vendor/cakephp/cakephp/src/Http/Server.php(97): Cake\Http\Runner->run()
#12 /var/www/html/admin/webroot/index.php(40): Cake\Http\Server->run()
#13 {main}
Request URL: /consultations/ordermedicinesfilter.xlsx
How Fix this issue

**Comment by cewi** [comment]
Hi, Must say that i did not work on this for years. Cakephp is on Version 5 this Plugin is compatible only with Version 3. PhpExcel is also replaced by PHPSpreadsheet. Which Version do you use?

**Comment by vishalJS15318** [comment]
Use PhpExcel version v1.8.2.how can used PHPSpreadsheet in cakephp 3.8

**Comment by joeljpa** [comment]
"_Cakephp is on Version 5 this Plugin is compatible only with Version 3. PhpExcel is also replaced by PHPSpreadsheet._ "

And despite that, I doubt you'll be surprised that people still have to be using it. Thank you, cewi, for your work after all these years.

vishalJS15318: I happen to have this plugin running on my project with CakePHP 3.4 though. If you have the option, I strongly recommend you migrate to PHPSpreadsheet over the permanently archived PHPExcel. Then you wouldn't need to try to use this plugin and even get better up-to-date help for PHPSpreadsheet.

**Comment by cewi** [comment]
@vishalJS15318 : CakepPhp 3.8. is not longer [maintained](https://github.com/cakephp/cakephp/security).  If you've the option, please update to a supported version. You can also use a recent php version, then. 
As @joeljpa said Phpspreadsheet is much better than [Phpexcel](https://phpspreadsheet.readthedocs.io/en/latest/) and can be used easily with Cakephp 4 or 5 (even 3). That's one of the reasons, I did not develop newer versions of this plugin. 
If you've to stuck with 3.8 you could check my (not finished not tested!) [php-spreadsheet-version](https://github.com/cewi/excel/tree/phpspreadsheet) of this plugin. Use at your own risk - you've be warned.

Anyway: The error log above looks like there is an error already with loading your data, because error-handler middleware is fired before the PhpExcel error occurs (The last error says that the generated spreadsheet is corrupt and that is likely because there was no data, but an rendered error page. The error page could not be converted to an spreadsheet.
Good luck!

**Comment by vishalJS15318** [comment]
OK Thanks
